name: Run Python Tests
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on:
      steps:
        - uses: action/checkout@v2
        - name: Install Python 3
          - uses: actions/setup-python@v1
            with:
              python-version: 3.9
        - name: Install dependencies
          run:
            python -m pip install --upgrade pip
            pip install pytest
            pip install -r requirements.txt
        - name: Run tests with pytest
          run: pytest
